import type { Metadata } from "next";
import "./styles/globals.css";
import { Inter, Limelight } from "next/font/google";
import Navbar from "./components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const limelight = Limelight({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-limelight",
});

export const metadata: Metadata = {
  title: "Vylia - Official Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${limelight.variable}`}>
      <body className={`font-sans antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
